# Generated by Django 4.0.10 on 2023-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_faq_slug_alter_faqcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(default=' ', upload_to='partner', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartnerImage',
        ),
    ]
