# Generated by Django 3.2.15 on 2023-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Discription'),
        ),
    ]
