# Generated by Django 4.0.10 on 2023-03-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
    ]
