# Generated by Django 4.0.10 on 2023-04-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_department_position_user_cpf_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='designation',
        ),
    ]
