# Generated by Django 4.0.10 on 2023-04-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designation',
            new_name='Position',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Famale'), ('O', 'Other'), ('N', 'Not Specified')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Join Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='resign_date',
            field=models.DateField(blank=True, null=True, verbose_name='Resign Date'),
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
    ]
