# Generated by Django 4.0.10 on 2023-05-24 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget balance')),
                ('cost_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost balance')),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cash balance')),
                ('withdraw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Withdraw')),
                ('donation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Donation')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collaborator')),
            ],
            options={
                'verbose_name': 'Collaborator account',
                'verbose_name_plural': 'Collaborator accounts',
            },
        ),
        migrations.CreateModel(
            name='CollaboratorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR code')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collaborator')),
            ],
            options={
                'verbose_name': 'Collaborator payment',
                'verbose_name_plural': 'Collaborator payments',
            },
        ),
        migrations.CreateModel(
            name='CollaboratorPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaborators.collaboratorpayment', verbose_name='Collaborator payment')),
            ],
            options={
                'verbose_name': 'Collaborator payment details',
                'verbose_name_plural': 'Collaborator payment details',
            },
        ),
        migrations.DeleteModel(
            name='CollaboratorUser',
        ),
    ]
