# Generated by Django 4.0.10 on 2023-05-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('benefits', '0002_alter_benefit_description_alter_benefit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitprice',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benefits.benefit', verbose_name='Benefit'),
        ),
        migrations.AlterField(
            model_name='benefitprice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
    ]
