# Generated by Django 4.0.10 on 2023-04-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_client_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
