# Generated by Django 4.0.10 on 2023-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_client_country_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
