# Generated by Django 4.0.10 on 2023-04-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_client_cep_alter_client_city_alter_client_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain Name'),
        ),
    ]
